import type React from 'react';
import * as Icons from 'lucide-react';
import { MapPin } from 'lucide-react';

export const getMapIconComponent = (name: string): React.ElementType => {
  const Icon = Icons[name as keyof typeof Icons];
  return (Icon || MapPin) as React.ElementType;
};

export const AVAILABLE_ICONS: (keyof typeof Icons)[] = [
  'MapPin',
  'Utensils',
  'Coffee',
  'ShoppingBag',
  'ShoppingCart',
  'Store',
  'Bed',
  'Landmark',
  'Music',
  'Film',
  'Ticket',
  'Star',
  'Heart',
  'Flag',
  'Home',
  'Briefcase',
  'Camera',
  'Car',
  'Bus',
  'Bike',
  'Plane',
  'Train',
  'Ship',
  'Anchor',
  'Zap',
  'Award',
  'Trophy',
  'Medal',
  'Gift',
  'Beer',
  'Wine',
  'Martini',
  'Pizza',
  'Sandwich',
  'IceCream',
  'Cookie',
  'Cake',
  'Palmtree',
  'Mountain',
  'Tent',
  'TreeDeciduous',
  'Leaf',
  'Flower',
  'Footprints',
  'Sun',
  'Moon',
  'Cloud',
  'Umbrella',
  'Snowflake',
  'Flame',
  'Droplet',
  'Waves',
  'Dog',
  'Cat',
  'Bone',
  'Stethoscope',
  'HeartPulse',
  'Pill',
  'Cross',
  'School',
  'GraduationCap',
  'Book',
  'Library',
  'Dumbbell',
  'Gamepad2',
  'Puzzle',
  'Palette',
  'Brush',
  'Mic',
  'Headphones',
  'Radio',
  'Tv',
  'Laptop',
  'Smartphone',
  'Wifi',
  'BatteryCharging',
  'Plug',
  'Hammer',
  'Wrench',
  'Construction',
  'Factory',
  'Building',
  'Castle',
  'Church',
  'Banknote',
  'CreditCard',
  'PiggyBank',
  'Tag',
  'Clock',
  'Calendar',
  'Key',
  'Lock',
  'Shield',
  'Eye',
  'Search',
];

export const COLOR_PALETTES = [
  {
    name: 'Blue',
    class: 'blue-500',
    fill: 'fill-blue-500',
    stroke: 'stroke-blue-700',
    bg: 'bg-blue-500',
    border: 'border-blue-500',
    text: 'text-blue-500',
  },
  {
    name: 'Red',
    class: 'red-500',
    fill: 'fill-red-500',
    stroke: 'stroke-red-700',
    bg: 'bg-red-500',
    border: 'border-red-500',
    text: 'text-red-500',
  },
  {
    name: 'Green',
    class: 'green-500',
    fill: 'fill-green-500',
    stroke: 'stroke-green-700',
    bg: 'bg-green-500',
    border: 'border-green-500',
    text: 'text-green-500',
  },
  {
    name: 'Purple',
    class: 'purple-500',
    fill: 'fill-purple-500',
    stroke: 'stroke-purple-700',
    bg: 'bg-purple-500',
    border: 'border-purple-500',
    text: 'text-purple-500',
  },
  {
    name: 'Orange',
    class: 'orange-500',
    fill: 'fill-orange-500',
    stroke: 'stroke-orange-700',
    bg: 'bg-orange-500',
    border: 'border-orange-500',
    text: 'text-orange-500',
  },
  {
    name: 'Pink',
    class: 'pink-500',
    fill: 'fill-pink-500',
    stroke: 'stroke-pink-700',
    bg: 'bg-pink-500',
    border: 'border-pink-500',
    text: 'text-pink-500',
  },
  {
    name: 'Teal',
    class: 'teal-500',
    fill: 'fill-teal-500',
    stroke: 'stroke-teal-700',
    bg: 'bg-teal-500',
    border: 'border-teal-500',
    text: 'text-teal-500',
  },
  {
    name: 'Gray',
    class: 'gray-600',
    fill: 'fill-gray-600',
    stroke: 'stroke-gray-800',
    bg: 'bg-gray-600',
    border: 'border-gray-600',
    text: 'text-gray-600',
  },
];

export const getColorByName = (name: string) => {
  return COLOR_PALETTES.find((c) => c.name === name) || COLOR_PALETTES[0];
};
